name: pytorch_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - pettingzoo=1.24.3
  - pandas=2.0.3
  - pillow=10.4.0
  - gymnasium=0.29.1
  - pygame=2.6.0
  - numpy=1.24.4
  - matplotlib=3.7.3
  - tensorboard=2.17.1
  - pip=24.2
  - stable-baselines3=2.3.2
  - pip:
      - supersuit==3.9.3